
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const LOGIN_ERR = "LOGIN_ERR";

export const SIGNUP_ERR = "SIGNUP_ERR";

export const LOADING_ON = "LOADING_ON";

export const LOADING_OFF = "LOADING_OFF";

export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";

export const GET_DATA_ERR = "GET_DATA_ERR";

export const SEND_FILE_SUCCESS = "SEND_FILE_SUCCESS";

export const SEND_FILE_ERR = "SEND_FILE_ERR";

export const UPDATE_PROIMG_SUCCESS = "UPDATE_PROIMG_SUCCESS";

export const UPDATE_PROIMG_ERR = "UPDATE_PROIMG_ERR";

export const IMAGE_UPDATE = "IMAGE_UPDATE";

export const SCHOOL_UPDATE = "SCHOOL_UPDATE";

export const CLASS_UPDATE = "CLASS_UPDATE";

export const DEGREE_UPDATE = "DEGREE_UPDATE";

export const EXPERIENCE_UPDATE = "EXPERIENCE_UPDATE";

export const PROFILE_NOTE_RESET = "PROFILE_NOTE_RESET";

export const UPDATE_INFO_SUCCESS = "UPDATE_INFO_SUCCESS";

export const UPDATE_INFO_ERR = "UPDATE_INFO_ERR";
